import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import React from "react";
import dynamic from "next/dynamic";
import {ItemProvider} from "@/context/ItemContext";

const AppNavbar = dynamic(() => import("@/components/app-navbar"));
const Footer = dynamic(() => import("@/components/footer"));

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            data-new-gr-c-s-check-loaded="14.1235.0"
            data-gr-ext-installed=""
        >
        <AppNavbar/>
        <ItemProvider>
            {children}
        </ItemProvider>
        <Footer/>

        </body>
        </html>
    );
}
